server:
  port: 8080
  servlet:
    context-path: /
    
spring:     
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/getinthere?serverTimezone=Asia/Seoul
    username: getinthere
    password: getinthere1234
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  jackson:
    time-zone: Asia/Seoul